### ISSUE TITLE
Cannot get any application named PlistOxide

### ISSUE THREAD

**Issue by aleixsr** [ChefKissInc/PlistOxide#36]
### Operating System

macOS 12.7.4

### What is your CPU's model?

MD Ryzen 7 3700X 

### What is your GPU's model?

AMD Radeon RX 6600

### Please describe the behaviour in detail.

I compiled build.rs successfully and I get a ./build file, but when I run it I only get:
`cargo:rustc-env=MACOSX_DEPLOYMENT_TARGET=10.13`
Nothing else happens.

### What should've happened instead?

Run a GUI application.

### Bug report submission terms

- [X] I am using the latest commit of PlistOxide.
- [X] My OS and drivers are up to date.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, system modifications the likes of OCLP.

**Comment by VisualEhrmanntraut** [comment]
learn how to use Rust's tools before attempting to build an application written in it, or grab a build from the actions tab
